name: Build and deploy fullstack app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Build Backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Ensure the build output from frontend is available for backend
      - name: Move frontend build to backend
        run: |
          mv frontend/dist backend/frontend-dist

      # Zip the fullstack app for deployment
      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r backend.zip ./*

      # Upload Artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: fullstack-app
          path: backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: fullstack-app

      - name: Unzip artifact for deployment
        run: unzip backend.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB106C02563F4644803FE98818B9260A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_33A9E5F7601B48A08C56DDA849C37D1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE604528F885451E8FB24E34665D9936 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pawwsome'
          slot-name: 'Production'
          package: .
          